version: 2

before:
  hooks:
    - go mod tidy
    - cmd: go build -ldflags "-s -w -H=windowsgui" -o monitor/monitor.exe ./monitor
      env:
        - CGO_ENABLED=0
        - GOOS=windows
        - GOARCH=amd64

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: fast-https
    main: ./fast-https.go

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    binary: fast-https
    main: ./fast-https.go
    ldflags:
      - "-s -w -H=windowsgui"

archives:
  - id: unix
    ids:
      - unix
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - config/cert/.keep
      - config/conf.d/.keep
      - config/fast-https.json
      - config/fastcgi.conf
      - config/mime.json
      - docs/*
      - httpdoc/root/favicon.ico
      - httpdoc/root/index.html
      - logs/.keep
      - README.md

  - id: windows
    ids:
      - windows
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - config/cert/.keep
      - config/conf.d/.keep
      - config/fast-https.json
      - config/fastcgi.conf
      - config/mime.json
      - docs/*
      - httpdoc/root/favicon.ico
      - httpdoc/root/index.html
      - logs/.keep
      - README.md
      - src: monitor/monitor.exe
        dst: monitor.exe
        strip_parent: true

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "1.3.2-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
