# 使用官方CentOS 7镜像
FROM centos:7

# 设置环境变量
ENV Fast-Https_VERSION 1.3.2
ENV AUTHOR Jackiex

# 设置维护者信息
LABEL maintainer="Jackiex<812520785@qq.com>"

# 安装tar工具来解压gzip格式的压缩文件
RUN yum install -y tar

# 将程序压缩包拷贝到镜像中的临时目录（需要先编译好程序放到dis文件夹中）
COPY dist/fast-https_Linux_x86_64.tar.gz /tmp/

# 创建目标目录
RUN mkdir -p /usr/local/fast-https
ENV PATH $PATH:/usr/local/fast-https

# 解压缩程序到目标目录
RUN tar -xzf /tmp/fast-https_Linux_x86_64.tar.gz -C /usr/local/fast-https

# 设置工作目录
WORKDIR /usr/local/fast-https

# 暴露8080端口
EXPOSE 8080

# 执行程序中的命令文件
CMD ["./fast-https"]
